apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: sklearn-model
spec:
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: classifier
          image: your-docker-repo/sklearn_model:latest
    graph:
      name: classifier
      type: MODEL
    name: default
    replicas: 1
